# Generated by Django 5.0.4 on 2024-05-14 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='team',
        ),
        migrations.AddField(
            model_name='staff',
            name='car_brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rv.carbrand'),
            preserve_default=False,
        ),
    ]
