# Generated by Django 5.0.4 on 2024-05-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rv', '0002_remove_staff_team_staff_car_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='car_brand',
        ),
        migrations.AddField(
            model_name='staff',
            name='team',
            field=models.ManyToManyField(related_name='staff_members', to='rv.team'),
        ),
    ]
