# Generated by Django 5.0.4 on 2024-06-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rv', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(max_length=6),
        ),
    ]
