# Generated by Django 5.0.4 on 2024-06-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rv', '0005_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.CharField(default='description', max_length=100),
        ),
    ]
