# Generated by Django 5.0.4 on 2024-06-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rv', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
